name: Build, Push and Deploy Docker Image
run-name: Build, Push and Deploy Image
on: [push]
env:
  IMAGE_NAME: "alfian8/nginx-username"
jobs:
  build-push-image:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: Build Image
        run: docker build -t $IMAGE_NAME .
      - name: List Image
        run: docker images
      - name: Login to Docker Registry
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PASS }}
      - name: Push Image
        run: docker push $IMAGE_NAME

  deploy:
    needs: build-push-image
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: stop and remove existing container
        run: docker-compose down --rmi all
      - name: start container
        run: docker-compose up -d
      - name: view container
        run: docker-compose ps
      - name: check container
        run: curl localhost:8080
